version: "3"
services:
  # traefik:
  #   image: traefik:v2.5
  #   command: --api.insecure=true --providers.docker
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  # route:
  #   build:
  #     context: .
  #     dockerfile: router.Dockerfile
  #   ports:
  #   - 3001:80
  oss:
    build:
      context: .
      dockerfile: oss.Dockerfile
      # 此处默认从宿主机(host)环境变量中传参，在宿主机中需要提前配置 SecretId/SecretKey 环境变量
      args:
        - SecretId
        - SecretKey
    ports:
      - 8000:80